### ISSUE TITLE
Vue component not supported in vue 2.x

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-vue-components#22]
This issue occurs because  `vue3` was selected during the development mode of the  `vue-sfc` npm package.

- We can look into using `vue2` for development so it could work for both versions?

@ram-verida  @kalanamt  any thought on how to resolve this issue?

screenshot from browser 

- console :
<img width="511" alt="Screenshot 2022-01-31 at 13 00 02" src="https://user-images.githubusercontent.com/54280620/151790371-f76d1f45-f46a-4a34-a58e-8a4bc81d5084.png">

- Source code error :

<img width="511" alt="Screenshot 2022-01-31 at 13 00 14" src="https://user-images.githubusercontent.com/54280620/151790412-c5d145e2-7532-4273-9476-cd1c6ec6b934.png">

**Comment by tahpot** [comment]
We have limited resources. I'm comfortable if we say these are only Vue3 components.

@nick-verida ?

**Comment by nick-verida** [comment]
Closing this.
