### ISSUE TITLE
Create a Verifiable Credential Fields display component

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-vue-components#33]
We need a new Vue component to display the fields in a Verifiable Credential. 

This will be used in the upcoming [VC display screen in the Account Explorer](https://github.com/verida/account-explorer/issues/71) and to replace the current VC display in the [Credential Management Platform](https://github.com/verida/Credentials-Management-Platform).

# Requirements

* The component should be passed a data array fields in `key:value` form
  * These fields generally will come from the decrypted credential, but the component **MUST NOT** be responsible for verification or decryption. This is because in most uses we'll want to use other parts of the credential (eg, who issued it etc) outside this component
* The component may optionally be passed a schema
  * The component  **MUST NOT** be responsible for retrieval of the schema
* Field naming should follow this algorithm:
  * If a schema has been passed AND if it contains `schema.properties` then:
    * if the schema has a `layout.view section`, only use the fields from there. Otherwise use all fields.
    * Look up each field name in `schema.properties`. If it exists use the title field for the label
   * Otherwise break field labels on CaseBreak (ie, CaseBreak becomes Case Break)
  * Otherwise break field labels on CaseBreak (ie, CaseBreak becomes Case Break)

## Styling

* The component must be flexible enough to allow for the ability to style fonts (size, name etc), width of component, colours.
* If other things are needed to match the display in the Credential Management Platform they should be implemented
* This component itself needs to be able to implement this display: 

![image](https://user-images.githubusercontent.com/87622993/156675525-d6975bc3-0898-4f60-a561-3ee259bd082c.png)

This is part of https://www.figma.com/file/KUUXMIaE7OyRwEdW173wr5/Account-Explorer-App?node-id=290%3A8072

# References

Current display in Credential Management Platform. Note that this display does NOT implement the algorithm above
<img width="400px" src="https://user-images.githubusercontent.com/87622993/155433444-b3993b97-9bc7-46db-9360-1fe51ebc5a39.png">

Current display in Vault. Note that this correctly implements the CamelCase Case Break. This schema does NOT have `schema.properties`:
<img width="400px" src="https://user-images.githubusercontent.com/87622993/155445995-496f6498-c4d4-433f-b154-60344855d834.png">

**Comment by cmcWebCode40** [comment]
This issue has been fixed in this PR https://github.com/verida/verida-vue-components/pull/44
