### ISSUE TITLE
Link from DID in Account is incorrect

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-vue-components#53]
![image](https://user-images.githubusercontent.com/87622993/161670570-2ed97fe4-2887-4478-9709-a37fdfd3cb33.png)

Think link hasn't been updated to include /did/

**Comment by cmcWebCode40** [comment]
@nick-verida , 

I did fixed this in this ticket #46  here is the line of code [line of code](https://github.com/verida/verida-vue-components/blob/183693e1eab181b0c59f153a93b658e4b5660ed0/components/account/src/lib-components/vda-account.vue#L28)
