### ISSUE TITLE
When logging in with a corrupted account cannot logout

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-vue-components#54]
If I have a corrupted account (created by Android version 0.2.3 build)

![image](https://user-images.githubusercontent.com/87622993/162643495-5e0213ae-18a1-453c-b303-ee435c2dc765.png)

These components should be robust in the event of errors. 

Instead it should probably something like setting the username to "unknown" and logging the exception to the console instead.

In general exceptions aren't suitable for end users and we should never have a case where the end user has to manually clear local storage to get to a workable state

**Comment by cmcWebCode40** [comment]
@nick-verida , 

Please how do I reproduce this error ?

is there a way I can log in with a corrupted account in order to test from my end as well ?

**Comment by cmcWebCode40** [comment]
FIxed in this PR https://github.com/verida/verida-vue-components/pull/58
