### ISSUE TITLE
vue-components should use `hasSession` instead of implementing own session persistence

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-vue-components#57]
See https://github.com/verida/verida-js/issues/182#issuecomment-1093978259

**Comment by nick-verida** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Verida-Engineering-61ef8aa39c1cb9001f7cb0ca/issues/verida/verida-vue-components/57?planning-poker) with ZenHub @cmcWebCode40

**Comment by cmcWebCode40** [comment]
Fixed in this PR https://github.com/verida/verida-vue-components/pull/58
