### ISSUE TITLE
DID showing incorrectly

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-vue-components#88]
In version `@verida/vue-account": "^0.1.38"` the DID is showing up incorrectly:

![image](https://user-images.githubusercontent.com/87622993/213610234-638883a1-29e2-4b8a-8e0a-821203b89e47.png)

(as seen on https://explorer.verida.network/).

It should show `did:vda:testnet:0x69...14d` or similar.

If that is too long, perhaps `did:vda:testnet:...14d` would work?

**Comment by cmcWebCode40** [comment]
> 

I think `did:vda:testnet` is about 14 characters which is already long for the space it contains, but I will try the second format

**Comment by aurelticot** [comment]
@nick-verida could we define a global guideline, such as DID method + 8 characters (or 6 characters)?

The DID method being everything before the last ":" (included), so "did:vda:" but also "did:vda:testnet:", "did:ether:", ...

**Comment by nick-verida** [comment]
It's a harder problem than it seems. You want to show the account the user is on, so that has to include some of the hex string. If the did method name is overly long that reduces the information. 

But you also want to show if they are on testnet. 

I think for now assuming it is `did:vda` is ok. There's a lot of things we'd need to change before other DID methods work

**Comment by aurelticot** [comment]
> It's a harder problem than it seems. You want to show the account the user is on, so that has to include some of the hex string. If the did method name is overly long that reduces the information.
> 
> But you also want to show if they are on testnet.
> 
> I think for now assuming it is `did:vda` is ok. There's a lot of things we'd need to change before other DID methods work

Yes, that's my point. displaying the did method (potentially with testnet) + X characters of the hex string

**Comment by nick-verida** [comment]
Yes, but I don't want us to consider non-`did:vda:` methods for now.

**Comment by aurelticot** [comment]
It could just be a generic and future-proof function to truncate doing a split on ":", so not more difficult than any other way.
